[build]
target = "x86_64-unknown-none"
rustflags = ["-C", "link-args=-T linker.ld", "-C", "link-args=--nmagic", "-C", "relocation-model=static"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.release]
opt-level = 3
lto = true
